version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: neondb
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: HBKNQbl3dp8j
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    external: true
